"""Publiczne API rozwiązywania Zagrożeń.

Cały runtime Modułu 1 jest skupiony w :mod:`rg_engine.threats`. Ten moduł jest
warstwą zgodności dla starszych importów `world_problems`.
"""

from rg_engine.threats import (
    PROBLEM_ACTION_COST,
    ProblemAttemptSession,
    active_threat_effects,
    available_problem_methods,
    begin_problem_attempt,
    can_begin_problem_attempt,
    clear_problem_retry_blocks,
    failure_revealed,
    failure_text,
    finish_problem_combat,
    is_interaction_blocked,
    is_tile_entry_blocked,
    marker_count,
    marker_is_resolved,
    marker_state,
    method_costs,
    method_requirements,
    method_state,
    parse_marker_ref,
    problem_retry_blocked,
    reset_threat_runtime,
    resolve_problem_method,
    reward_text,
    set_marker_tile,
    set_problem_combat_launcher,
    threat_display_number,
    threat_modifier,
    threat_runtime_snapshot,
    unresolved_marker_ids,
    validate_problem_definition,
)

__all__ = [
    "PROBLEM_ACTION_COST",
    "ProblemAttemptSession",
    "active_threat_effects",
    "available_problem_methods",
    "begin_problem_attempt",
    "can_begin_problem_attempt",
    "clear_problem_retry_blocks",
    "failure_revealed",
    "failure_text",
    "finish_problem_combat",
    "is_interaction_blocked",
    "is_tile_entry_blocked",
    "marker_count",
    "marker_is_resolved",
    "marker_state",
    "method_costs",
    "method_requirements",
    "method_state",
    "parse_marker_ref",
    "problem_retry_blocked",
    "reset_threat_runtime",
    "resolve_problem_method",
    "reward_text",
    "set_marker_tile",
    "set_problem_combat_launcher",
    "threat_display_number",
    "threat_modifier",
    "threat_runtime_snapshot",
    "unresolved_marker_ids",
    "validate_problem_definition",
]
